### ISSUE TITLE
Cant render tilemap to custom render target

### ISSUE THREAD

**Issue by fossegutten** [forbjok/bevy_simple_tilemap#10] opened 2023-01-10 08:34 UTC
Would be nice to be able to set a custom image handle to render the tilemap to

Example:
Gray area is my render target, where the sprites are rendered. Purple area is "black borders". Tilemap always gets rendered directly to the main image buffer it seems.

![image](https://user-images.githubusercontent.com/15088582/211500362-b96f0675-be03-46f2-bcc7-82d8fccf70be.png)

**Comment by forbjok** [comment] 2023-01-31 15:16
Do you have a minimal reproduction project for this issue?

**Comment by forbjok** [comment] 2023-01-31 19:00
I made a "render to texture" example based on the Bevy example of the same name, with a tilemap being rendered onto the cube instead of another cube. As far as I can tell it's working.

It's available in a branch: https://github.com/forbjok/bevy_simple_tilemap/tree/render-to-texture-example

**Comment by forbjok** [comment] 2023-07-09 21:46
Closing as resolved, since there hasn't been any new comments in a long time.

**Closed by forbjok** 2023-07-09 21:46 UTC
